DEV: Simplify multisite:migrate to call Process.fork directly (#39366)
Each `multisite:migrate` child process buffers its output in an instance of `StringIO` held in memory. When a child crashes unexpectedly, the buffer dies with it and we only get generic error traces like the following from the `parallel` gem:

```
Parallel::DeadWorker: Parallel::DeadWorker (Parallel::DeadWorker)
/var/www/discourse/vendor/bundle/ruby/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:83:in 'Parallel::Worker#work'
...

Caused by:
EOFError: end of file reached (EOFError)
/var/www/discourse/vendor/bundle/ruby/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:81:in 'Parallel::Worker#work'
...
```

This PR replaces the `parallel` gem with `Process.fork`. Databases are sharded across multiple child processes where each child process reopens stdout/stderr to a temp log file. The trade-off here is that logs are no longer streamed to the parent's stdout as they are written in the child process. This is OK since it is rare for someone to be watching the logs while running migrations for multisite and we also get to reduce a huge amount of complexity if we don't have to stream the logs from child to parent.